Collection hover focus
AiHikki/project-DataDynasty01 pull request #7
Opened 2023-10-02 16:52 UTC by Sinfinka

Додані вспливаючі вікна при ховері\фокусі. Також зміна кольору заголовків карток при ховері\фокусі.

Виправилена опечатка в класі параграфів.

2023-10-03 14:19 UTC, AiHikki requested changes

2023-10-03 14:19 UTC, AiHikki commented on src/css/collection.css
> +  text-align: left;
Здається ця властивість зайва, немає жодного ефекту

2023-10-03 14:19 UTC, AiHikki commented on src/css/collection.css
> +  gap: 10px;
так як є justify-content: space-between;
gap немає ефекту. Можна або забрати gap або justify-content

2023-10-04 20:02 UTC, Sinfinka commented on src/css/collection.css
> +  text-align: left;
Прибрала   text-align: left;

2023-10-04 20:02 UTC, Sinfinka commented on src/css/collection.css
> +  gap: 10px;
Прибрала   justify-content: space-between;

2023-10-04 20:34 UTC, AiHikki approved these changes

2023-10-04 20:34 UTC, merged