Hero
AiHikki/project-DataDynasty01 pull request #9
Opened 2023-10-02 18:21 UTC by IrynaYevcheva

2023-10-02 20:59 UTC, AiHikki requested changes

2023-10-02 20:59 UTC, AiHikki commented on src/css/hero.css
> +  padding: 14px 39px;
Падінги можна прибрати, так як є висота і ширина

2023-10-02 20:59 UTC, AiHikki commented on src/css/hero.css
> +  margin-bottom: 40px;
margin-bottom випадає за батьківський елемент, краще задати сюди
.title-button-container {margin-bottom: 40px;}

2023-10-02 20:59 UTC, AiHikki commented on src/css/hero.css
> +  .hero-title {
На планшетах і дальше margin-bottom: 40px;


ще можна змінити line-height, на планшетах і десктопі трошки відрізняється (ну це за бажанням)

2023-10-02 20:59 UTC, AiHikki commented on src/partials/hero.html
> +      <img
Ця картинка змінює розмір залежно від пристроя, і було б добре зробити за допомогою атрибуту sizes та srcset

2023-10-03 00:21 UTC, IrynaYevcheva commented on src/css/hero.css
> +  padding: 14px 39px;
Змінила

2023-10-03 00:22 UTC, IrynaYevcheva commented on src/css/hero.css
> +  margin-bottom: 40px;
Змінила

2023-10-03 00:27 UTC, IrynaYevcheva commented on src/css/hero.css
> +  .hero-title {
margin-bottom: 40px змінила (не догледіла, був тільки з 1280)

щодо  line-height: на плншеті і на 1280, там однакові значення, на 1440 зміну ситлів hero title прописала..., можливо, я не так щось зрозуміла.

2023-10-03 06:51 UTC, AiHikki commented on src/css/hero.css
> +  .hero-title {
Щодо line-height між телефоном і планшетом здається змінюється. Помилився(

2023-10-03 08:19 UTC, AiHikki approved these changes

2023-10-03 08:20 UTC, AiHikki approved these changes

2023-10-03 08:20 UTC, merged